name: 'Base Install Action'
description: 'Run basic installation steps for the benchmarking framework.'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'
        cache: 'pip'
    - name: Install Excalibur-tests
      shell: bash
      run: |
        if ! pip list 2> /dev/null | grep -q 'excalibur-tests'; then
          pip install -e .[test]
          pip install pandas
        fi
        if ! pip list 2> /dev/null | grep -q 'keystoneauth1'; then
          pip install keystoneauth1
        fi
        if ! pip list 2> /dev/null | grep -q 'python-swiftclient'; then
          pip install python-swiftclient
        fi
        if ! pip list 2> /dev/null | grep -q 'dotenv'; then
          pip install dotenv
        fi
    - name: Find & Install Spack
      id: fspack
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        export SPACK_PATH=$(which spack)
        if [ -z $SPACK_PATH ]; then
          if [ ! -d spack ]; then
            git clone --depth=1 --branch=releases/v1.1 https://github.com/spack/spack.git
          fi
          cd spack
          echo "PATH=${PWD}/bin:${PATH}" >> "${GITHUB_ENV}"
        fi