name: Deploy EoR Microbenchmark to runner
run-name: ${{ github.actor }} is running EoR Microbenchmark.
on:
  workflow_dispatch: {}
#  schedule:
#    - cron: "0 0 * * 1"
# "Minute Hour DayOfMonth(1-31) Month(1-12) DayOfWeek(0-6)"

jobs:
  # This searches the framework repo for all available runners and submits all workflows to them.
  discover-runners:
    runs-on: ubuntu-latest  # Use GitHub-hosted for discovery
    outputs:
      runmatrix: ${{ steps.set-matrix.outputs.runner-matrix }}
    steps:
      - uses: actions/checkout@v6
      - id: runner-retrieval
        uses: ./.github/actions/runner-retrieval
      - id: set-matrix
        shell: bash
        run: echo random-number ${{ steps.runner-retrieval.outputs.runmatrix }}

  run-eor:
    needs: discover-runners
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.discover-runners.outputs.runmatrix) }}
    runs-on: [self-hosted, "${{ runmatrix.runner }}"]
    environment: PRODUCTION
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/common-setup
      - name: Install Dependencies
        run: |
          pip install -r ${PWD}/benchmarks/apps/microbench-eor/requirements.txt
      - name: Run EoR Microbenchmark
        id: runcall
        # Run should contain all the lines of code in order to run the test
        shell: bash
        env:
          OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_AUTH_TYPE: ${{ vars.OS_AUTH_TYPE }}
          OS_IDENTITY_API_VERSION: ${{ vars.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ vars.OS_INTERFACE }}
          OS_REGION_NAME: ${{ vars.OS_REGION_NAME }}
        run: |
          export RFM_CONFIG_FILES="${PWD}/benchmarks/reframe_config.py"
          export RFM_USE_LOGIN_SHELL="true"
          export SPACK_ROOT=$(which spack)
          if [ -f "${SPACK_ROOT}/share/spack/setup-env.sh" ]; then
            source "${SPACK_ROOT}/share/spack/setup-env.sh"
          fi
          reframe --skip-sanity-check --system=${{ runmatrix.reframesystem }} -c ./benchmarks/apps/microbench-eor -n MicrobenchEOR -r