name: Deploy tests to remote runnter
run-name: ${{ github.actor }} is running.
on:
  workflow_dispatch: {}
#  schedule:
#    - cron: "0 0 * * 1"
# "Minute Hour DayOfMonth(1-31) Month(1-12) DayOfWeek(0-6)"

jobs:
  test-run: # Name of test to run
    runs-on: ubuntu-latest # Run on the self-hosted runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: 'pip'

      - name: Install Excalibur-tests
        shell: bash
        run: |
          pip install -e .
          pip install pandas

      - name: Install Spack
        shell: bash
        working-directory: ${{runner.workspace}}
        run: |
          git clone --depth=1 --branch=releases/v1.1 https://github.com/spack/spack.git
          cd spack
          echo "PATH=${PWD}/bin:${PATH}" >> "${GITHUB_ENV}"

      - name: Find Spack
        id: fspack
        shell: bash
        run: |
          export SPACK_PATH=$(which spack)
          if [ -z $SPACK_PATH ]; then
            echo "installed=false" >> "$GITHUB_OUTPUT"
          else
            echo "installed=true" >> "$GITHUB_OUTPUT"
            echo "spack_path=$SPACK_PATH" >> "$GITHUB_OUTPUT"
          fi

      # add installation and run steps for specific test
      - name: Install stuff
        shell: bash
        run: |
          echo "Install commands"

      - name: Run stuff
        id: runcall
        # Run should contain all the lines of code in order to run the test
        shell: bash
        run: |
          echo "Run commands"